// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4SSF7cjEzDZ34f_OfuT-LfnCPlJSd81I',
    appId: '1:480752722157:web:5e8c3a65a8c304389c2ce4',
    messagingSenderId: '480752722157',
    projectId: 'work-shift-automator',
    authDomain: 'work-shift-automator.firebaseapp.com',
    storageBucket: 'work-shift-automator.appspot.com',
    measurementId: 'G-9MRTTXF8NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTy3ebnIpGMj3Fi6t9z0DD0JDEAsT9V0U',
    appId: '1:480752722157:android:8f7bbb7690e597189c2ce4',
    messagingSenderId: '480752722157',
    projectId: 'work-shift-automator',
    storageBucket: 'work-shift-automator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj8-iCr7Op0Gd3-5jKnfozFTfV3RiVjFU',
    appId: '1:480752722157:ios:a9ac90643398a8dd9c2ce4',
    messagingSenderId: '480752722157',
    projectId: 'work-shift-automator',
    storageBucket: 'work-shift-automator.appspot.com',
    iosClientId: '480752722157-d2geam0748jb7qjikbd0cfflbm74d69m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shift20230530',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj8-iCr7Op0Gd3-5jKnfozFTfV3RiVjFU',
    appId: '1:480752722157:ios:f88d036ea07bcfff9c2ce4',
    messagingSenderId: '480752722157',
    projectId: 'work-shift-automator',
    storageBucket: 'work-shift-automator.appspot.com',
    iosClientId: '480752722157-tc386hj946r1t1g3c9j6g5gpn3fo8j00.apps.googleusercontent.com',
    iosBundleId: 'com.example.shift.RunnerTests',
  );
}
